-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 14:53:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mail`
  DEFAULT CHARACTER SET utf8;
USE `mail`;

-- -----------------------------------------------------
-- Table `mail`.`maildrop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`maildrop` (
  `login`    VARCHAR(20)                 NOT NULL,
  `password` CHAR(32)                    NOT NULL,
  `state`    ENUM ('locked', 'unlocked') NOT NULL DEFAULT 'unlocked',
  PRIMARY KEY (`login`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mail`.`mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`mail` (
  `id`       INT                        NOT NULL AUTO_INCREMENT,
  `sender`   VARCHAR(20)                NOT NULL,
  `receiver` VARCHAR(20)                NOT NULL,
  `body`     BLOB                       NOT NULL,
  `date`     DATETIME                   NOT NULL,
  `subject`  VARCHAR(45)                NOT NULL,
  `state`    ENUM ('actual', 'deleted') NOT NULL DEFAULT 'actual',
  PRIMARY KEY (`id`),
  INDEX `fk_mail_sender_user_login_idx` (`sender` ASC),
  INDEX `fk_mail_receiver_user_login_idx` (`receiver` ASC),
  CONSTRAINT `fk_mail_sender_user_login`
  FOREIGN KEY (`sender`)
  REFERENCES `mail`.`maildrop` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mail_receiver_user_login`
  FOREIGN KEY (`receiver`)
  REFERENCES `mail`.`maildrop` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;


INSERT INTO maildrop (login, password) VALUES
  ('Pavel', '1234'),
  ('login1', '1234'),
  ('login2', '228');

INSERT INTO mail (sender, receiver, body, date, subject) VALUES
  ('Pavel', 'login1', '4e kak dela', '2016-1-23 18:54:38', 'ku'),
  ('login1', 'Pavel', 'norm', '2016-1-23 18:54:40', 'kuku'),
  ('login1', 'Pavel', 'privet', '2016-1-23 18:54:50', 'kk');


